In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URLs for the webpages we want to scrape
urls = [
    "https://www.transfermarkt.com/poland/kader/verein/3442/plus/1/galerie/0?saison_id=2022",
    "https://www.transfermarkt.com/argentina/kader/verein/3437/plus/1/galerie/0?saison_id=2022",
    "https://www.transfermarkt.com/mexico/kader/verein/6303/plus/1/galerie/0?saison_id=2022",
    "https://www.transfermarkt.com/saudi-arabia/kader/verein/3807/plus/1/galerie/0?saison_id=2022",
    "https://www.transfermarkt.com/japan/kader/verein/3435/plus/1/galerie/0?saison_id=2022",
    "https://www.transfermarkt.com/spain/kader/verein/3375/plus/1/galerie/0?saison_id=2022",
    "https://www.transfermarkt.com/germany/kader/verein/3262/plus/1/galerie/0?saison_id=2022",
    "https://www.transfermarkt.com/costa-rica/kader/verein/8497/plus/1/galerie/0?saison_id=2022"
]

# Headers to send with the request
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'}

# Initialize an empty list to store the player data
players = []

# Loop through each URL
for url in urls:

    # Make a GET request to the webpage
    response = requests.get(url, headers=headers)

    # Parse the HTML content of the webpage
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find all of the table rows in the HTML
    rows = soup.find_all('tr')


    # Loop through each table row
    for row in rows:
        # Find all of the table cells in the row
        cells = row.find_all('td')
        # If there are at least 7 cells, then we know it's a player row
        if len(cells) >= 7:
            name = cells[3].text.strip()
            dob = cells[5].text.strip()
            height = cells[7].text.strip()
            position = cells[4].text.strip()
            market_value = cells[12].text.strip()
            better_foot = cells[8].text.strip()
            team = url.split('/')[3].capitalize()

            # Add a dictionary containing the player data to the list
            players.append({'Name': name, 'Date_of_birth': dob, 'Height_cm': height, 'Position': position, 'Market_value': market_value, 'Better_foot': better_foot, 'Team': team})

# Create a Pandas DataFrame from the list of player dictionaries
df = pd.DataFrame(players)

missing = pd.read_csv('missing_players.csv')

df = pd.concat([df, missing], axis=0, ignore_index=True)

df.to_csv('players.csv')

# Print the DataFrame
df

,Name,Date_of_birth,Height_cm,Position,Market_value,Better_foot,Team
0,Wojciech Szczesny,"Apr 18, 1990 (32)","1,96m",Goalkeeper,€13.00m,right,Poland
1,Kamil Grabara,"Jan 8, 1999 (24)","1,95m",Goalkeeper,€5.00m,right,Poland
2,Lukasz Skorupski,"May 5, 1991 (31)","1,87m",Goalkeeper,€3.00m,right,Poland
3,Jan Bednarek,"Apr 12, 1996 (26)","1,89m",Centre-Back,€18.00m,right,Poland
4,Jakub Kiwior,"Feb 15, 2000 (22)","1,89m",Centre-Back,€8.00m,left,Poland
...,...,...,...,...,...,...,...
212,Salem Al-Dawsari,"Aug 19, 1991 (30)","1,71m",Left Winger,€2.80m,right,Saudi-arabia
213,Hattan Bahebri,"Jul 16, 1992 (29)","1,70m",Right Winger,€900k,right,Saudi-arabia
214,Firas Al-Buraikan,"May 14, 2000 (22)","1,81m",Centre-Forward,€1.20m,left,Saudi-arabia
215,Saleh Al-Shehri,"Nov 1, 1993 (28)","1,84m",Centre-Forward,€1.00m,right,Saudi-arabia
216,Sergio Busquets,"Jul 16, 1988 (33)","1,89m",Defensive Midfield,€9.00m,right,Spain

In [10]:
import pandas as pd

data = [
    {'Team_name': 'Argentina', 'Coach': 'Lionel Scaloni', 'Captain': 'Lionel Messi', 'Group_letter': 'C', 'Wins': 2, 'Draws': 0, 'Losses': 1, 'Goals_for': 5, 'Goals_against': 2, 'Points': 6},
    {'Team_name': 'Poland', 'Coach': 'Czeslaw Michniewicz', 'Captain': 'Robert Lewandowski', 'Group_letter': 'C', 'Wins': 1, 'Draws': 1, 'Losses': 1, 'Goals_for': 2, 'Goals_against': 2, 'Points': 4},
    {'Team_name': 'Mexico', 'Coach': 'Gerardo Martino', 'Captain': 'Andres Guardado', 'Group_letter': 'C', 'Wins': 1, 'Draws': 1, 'Losses': 1, 'Goals_for': 2, 'Goals_against': 3, 'Points': 4},
    {'Team_name': 'Saudi Arabia', 'Coach': 'Herve Renard', 'Captain': 'Salman Al-Faraj', 'Group_letter': 'C', 'Wins': 1, 'Draws': 0, 'Losses': 2, 'Goals_for': 3, 'Goals_against': 5, 'Points': 3},
    {'Team_name': 'Japan', 'Coach': 'Hajime Moriyasu', 'Captain': 'Maya Yoshida', 'Group_letter': 'E', 'Wins': 2, 'Draws': 0, 'Losses': 1, 'Goals_for': 4, 'Goals_against': 3, 'Points': 6},
    {'Team_name': 'Spain', 'Coach': 'Luis de la Fuente', 'Captain': 'Sergio Busquets', 'Group_letter': 'E', 'Wins': 1, 'Draws': 1, 'Losses': 1, 'Goals_for': 9, 'Goals_against': 3, 'Points': 4},
    {'Team_name': 'Germany', 'Coach': 'Hansi Flick', 'Captain': 'Manuel Neuer', 'Group_letter': 'E', 'Wins': 1, 'Draws': 1, 'Losses': 1, 'Goals_for': 6, 'Goals_against': 5, 'Points': 4},
    {'Team_name': 'Costa Rica', 'Coach': 'Luis Fernando Suarez', 'Captain': 'Bryan Ruiz', 'Group_letter': 'E', 'Wins': 1, 'Draws': 0, 'Losses': 2, 'Goals_for': 3, 'Goals_against': 11, 'Points': 3},
]

df = pd.DataFrame(data)
df.to_csv('teams.csv')

df

,Team_name,Coach,Captain,Group_letter,Wins,Draws,Losses,Goals_for,Goals_against,Points
0,Argentina,Lionel Scaloni,Lionel Messi,C,2,0,1,5,2,6
1,Poland,Czeslaw Michniewicz,Robert Lewandowski,C,1,1,1,2,2,4
2,Mexico,Gerardo Martino,Andres Guardado,C,1,1,1,2,3,4
3,Saudi Arabia,Herve Renard,Salman Al-Faraj,C,1,0,2,3,5,3
4,Japan,Hajime Moriyasu,Maya Yoshida,E,2,0,1,4,3,6
5,Spain,Luis de la Fuente,Sergio Busquets,E,1,1,1,9,3,4
6,Germany,Hansi Flick,Manuel Neuer,E,1,1,1,6,5,4
7,Costa Rica,Luis Fernando Suarez,Bryan Ruiz,E,1,0,2,3,11,3

In [11]:
import pandas as pd

data = [
    {'Stadium_name': 'Al Bayt Stadium', 'City': 'Al Khor City', 'Capacity': 68895},
    {'Stadium_name': 'Lusail Stadium', 'City': 'Lusail City', 'Capacity': 88966},
    {'Stadium_name': 'Ahmad Bin Ali Stadium', 'City': 'Umm Al Afaei', 'Capacity': 45032},
    {'Stadium_name': 'Al Janoub Stadium', 'City': 'Al Wakrah', 'Capacity': 44325},
    {'Stadium_name': 'Al Thumama Stadium', 'City': 'Al Thumama Stadium', 'Capacity': 44400},
    {'Stadium_name': 'Education City Stadium', 'City': 'Al Rayyan', 'Capacity': 44667},
    {'Stadium_name': 'Khalifa International Stadium', 'City': 'Aspire', 'Capacity': 45857},
    {'Stadium_name': 'Stadium 974', 'City': 'Al Thumama Stadium', 'Capacity': 44089},
]

df = pd.DataFrame(data)
df.to_csv('stadiums.csv')

df

                    Stadium_name                City  Capacity
0                Al Bayt Stadium        Al Khor City     68895
1                 Lusail Stadium         Lusail City     88966
2          Ahmad Bin Ali Stadium        Umm Al Afaei     45032
3              Al Janoub Stadium           Al Wakrah     44325
4             Al Thumama Stadium  Al Thumama Stadium     44400
5         Education City Stadium           Al Rayyan     44667
6  Khalifa International Stadium              Aspire     45857
7                    Stadium 974  Al Thumama Stadium     44089

In [12]:
import pandas as pd

data = [
    {'stadium': 'Khalifa International Stadium', 'date': '23-11-2022', 'time': '14:00', 'home_team': 'Germany', 'away_team': 'Japan', 'home_goals': 1, 'away_goals': 2},
    {'stadium': 'Al-Thumama Stadium', 'date': '23-11-2022', 'time': '17:00', 'home_team': 'Spain', 'away_team': 'Costa Rica', 'home_goals': 7, 'away_goals': 0},
    {'stadium': 'Ahmad bin Ali Stadium', 'date': '27-11-2022', 'time': '11:00', 'home_team': 'Japan', 'away_team': 'Costa Rica', 'home_goals': 0, 'away_goals': 1},
    {'stadium': 'Al-Bayt Stadium', 'date': '27-11-2022', 'time': '20:00', 'home_team': 'Spain', 'away_team': 'Germany', 'home_goals': 1, 'away_goals': 1},
    {'stadium': 'Khalifa International Stadium', 'date': '01-12-2022', 'time': '20:00', 'home_team': 'Japan', 'away_team': 'Spain', 'home_goals': 2, 'away_goals': 1},
    {'stadium': 'Al-Bayt Stadium', 'date': '01-12-2022', 'time': '20:00', 'home_team': 'Costa Rica', 'away_team': 'Germany', 'home_goals': 2, 'away_goals': 4},
    {'stadium': 'Lusail Iconic Stadium', 'date': '22-11-2022', 'time': '11:00', 'home_team': 'Argentina', 'away_team': 'Saudi Arabia', 'home_goals': 1, 'away_goals': 2},
    {'stadium': 'Stadium 974', 'date': '22-11-2022', 'time': '17:00', 'home_team': 'Mexico', 'away_team': 'Poland', 'home_goals': 0, 'away_goals': 0},
    {'stadium': 'Education City Stadium', 'date': '26-11-2022', 'time': '14:00', 'home_team': 'Poland', 'away_team': 'Saudi Arabia', 'home_goals': 2, 'away_goals': 0},
    {'stadium': 'Lusail Iconic Stadium', 'date': '26-11-2022', 'time': '20:00', 'home_team': 'Argentina', 'away_team': 'Mexico', 'home_goals': 2, 'away_goals': 0},
    {'stadium': 'Lusail Iconic Stadium', 'date': '30-11-2022', 'time': '20:00', 'home_team': 'Saudi Arabia', 'away_team': 'Mexico', 'home_goals': 1, 'away_goals': 2},
    {'stadium': 'Stadium 974', 'date': '30-11-2022', 'time': '20:00', 'home_team': 'Poland', 'away_team': 'Argentina', 'home_goals': 0, 'away_goals': 2},
]

df = pd.DataFrame(data)
df.to_csv('matches.csv')

df

,stadium,date,time,home_team,away_team,home_goals,away_goals
0,Khalifa International Stadium,23-11-2022,14:00,Germany,Japan,1,2
1,Al-Thumama Stadium,23-11-2022,17:00,Spain,Costa Rica,7,0
2,Ahmad bin Ali Stadium,27-11-2022,11:00,Japan,Costa Rica,0,1
3,Al-Bayt Stadium,27-11-2022,20:00,Spain,Germany,1,1
4,Khalifa International Stadium,01-12-2022,20:00,Japan,Spain,2,1
5,Al-Bayt Stadium,01-12-2022,20:00,Costa Rica,Germany,2,4
6,Lusail Iconic Stadium,22-11-2022,11:00,Argentina,Saudi Arabia,1,2
7,Stadium 974,22-11-2022,17:00,Mexico,Poland,0,0
8,Education City Stadium,26-11-2022,14:00,Poland,Saudi Arabia,2,0
9,Lusail Iconic Stadium,26-11-2022,20:00,Argentina,Mexico,2,0
10,Lusail Iconic Stadium,30-11-2022,20:00,Saudi Arabia,Mexico,1,2
11,Stadium 974,30-11-2022,20:00,Poland,Argentina,0,2

In [13]:
import pandas as pd

data = [
    {'player': 'Alexis Mac Allister', 'match': 'Poland-Argentina', 'minute': 46, 'type': 'G'},
    {'player': 'Nahuel Molina', 'match': 'Poland-Argentina', 'minute': 46, 'type': 'A'},
    {'player': 'Julian Alvarez', 'match': 'Poland-Argentina', 'minute': 67, 'type': 'G'},
    {'player': 'Enzo Fernandez', 'match': 'Poland-Argentina', 'minute': 67, 'type': 'A'},
    {'player': 'Marcos Acuna', 'match': 'Poland-Argentina', 'minute': 49, 'type': 'Y'},
    {'player': 'Grzegorz Krychowiak', 'match': 'Poland-Argentina', 'minute': 78, 'type': 'Y'},
    {'player': 'Henry Martin', 'match': 'Saudi Arabia-Mexico', 'minute': 47, 'type': 'G'},
    {'player': 'Cesar Montes', 'match': 'Saudi Arabia-Mexico', 'minute': 47, 'type': 'A'},
    {'player': 'Luis Chavez', 'match': 'Saudi Arabia-Mexico', 'minute': 52, 'type': 'G'},
    {'player': 'Salem Al-Dawsari', 'match': 'Saudi Arabia-Mexico', 'minute': 95, 'type': 'G'},
    {'player': 'Hattan Bahebri', 'match': 'Saudi Arabia-Mexico', 'minute': 95, 'type': 'A'},
    {'player': 'Edson Alvarez', 'match': 'Saudi Arabia-Mexico', 'minute': 16, 'type': 'Y'},
    {'player': 'Saleh Al-Shehri', 'match': 'Saudi Arabia-Mexico', 'minute': 28, 'type': 'Y'},
    {'player': 'Ali Al-Hassan', 'match': 'Saudi Arabia-Mexico', 'minute': 34, 'type': 'Y'},
    {'player': 'Hassan Tambakti', 'match': 'Saudi Arabia-Mexico', 'minute': 52, 'type': 'Y'},
    {'player': 'Abdullah Madu', 'match': 'Saudi Arabia-Mexico', 'minute': 81, 'type': 'Y'},
    {'player': 'Abdulelah Al-Amri', 'match': 'Saudi Arabia-Mexico', 'minute': 91, 'type': 'Y'},
    {'player': 'Hattan Bahebri', 'match': 'Saudi Arabia-Mexico', 'minute': 97, 'type': 'Y'},
    {'player': 'Lionel Messi', 'match': 'Argentina-Mexico', 'minute': 64, 'type': 'G'},
    {'player': 'Angel Di Maria', 'match': 'Argentina-Mexico', 'minute': 64, 'type': 'A'},
    {'player': 'Enzo Fernandez', 'match': 'Argentina-Mexico', 'minute': 87, 'type': 'G'},
    {'player': 'Lionel Messi', 'match': 'Argentina-Mexico', 'minute': 87, 'type': 'A'},
    {'player': 'Nestor Araujo', 'match': 'Argentina-Mexico', 'minute': 22, 'type': 'Y'},
    {'player': 'Gonzalo Montiel', 'match': 'Argentina-Mexico', 'minute': 43, 'type': 'Y'},
    {'player': 'Erick Gutierrez', 'match': 'Argentina-Mexico', 'minute': 50, 'type': 'Y'},
    {'player': 'Hector Herrera', 'match': 'Argentina-Mexico', 'minute': 66, 'type': 'Y'},
    {'player': 'Roberto Alvarado', 'match': 'Argentina-Mexico', 'minute': 89, 'type': 'Y'},
    {'player': 'Piotr Zielinski', 'match': 'Poland-Saudi Arabia', 'minute': 39, 'type': 'G'},
    {'player': 'Robert Lewandowski', 'match': 'Poland-Saudi Arabia', 'minute': 39, 'type': 'A'},
    {'player': 'Robert Lewandowski', 'match': 'Poland-Saudi Arabia', 'minute': 82, 'type': 'G'},
    {'player': 'Jakub Kiwior', 'match': 'Poland-Saudi Arabia', 'minute': 15, 'type': 'Y'},
    {'player': 'Matty Cash', 'match': 'Poland-Saudi Arabia', 'minute': 16, 'type': 'Y'},
    {'player': 'Arkadiusz Milik', 'match': 'Poland-Saudi Arabia', 'minute': 19, 'type': 'Y'},
    {'player': 'Abdulelah Al-Malki', 'match': 'Poland-Saudi Arabia', 'minute': 21, 'type': 'Y'},
    {'player': 'Abdulelah Al-Amri', 'match': 'Poland-Saudi Arabia', 'minute': 45, 'type': 'Y'},
    {'player': 'Jorge Sanchez', 'match': 'Mexico-Poland', 'minute': 29, 'type': 'Y'},
    {'player': 'Hector Moreno', 'match': 'Mexico-Poland', 'minute': 56, 'type': 'Y'},
    {'player': 'Przemyslaw Frankowski', 'match': 'Mexico-Poland', 'minute': 76, 'type': 'Y'},
    {'player': 'Lionel Messi', 'match': 'Argentina-Saudi Arabia', 'minute': 10, 'type': 'G'},
    {'player': 'Leandro Paredes', 'match': 'Argentina-Saudi Arabia', 'minute': 10, 'type': 'A'},
    {'player': 'Saleh Al-Shehri', 'match': 'Argentina-Saudi Arabia', 'minute': 48, 'type': 'G'},
    {'player': 'Firas Al-Buraikan', 'match': 'Argentina-Saudi Arabia', 'minute': 48, 'type': 'A'},
    {'player': 'Salem Al-Dawsari', 'match': 'Argentina-Saudi Arabia', 'minute': 53, 'type': 'G'},
    {'player': 'Abdulelah Al-Malki', 'match': 'Argentina-Saudi Arabia', 'minute': 67, 'type': 'Y'},
    {'player': 'Ali Al-Boleahi', 'match': 'Argentina-Saudi Arabia', 'minute': 75, 'type': 'Y'},
    {'player': 'Salem Al-Dawsari', 'match': 'Argentina-Saudi Arabia', 'minute': 79, 'type': 'Y'},
    {'player': 'Saud Abdulhamid', 'match': 'Argentina-Saudi Arabia', 'minute': 82, 'type': 'Y'},
    {'player': 'Nawaf Al-Abed', 'match': 'Argentina-Saudi Arabia', 'minute': 88, 'type': 'Y'},
    {'player': 'Mohammed Al-Owais', 'match': 'Argentina-Saudi Arabia', 'minute': 90, 'type': 'Y'},
    {'player': 'Ilkay Gundogan', 'match': 'Germany-Japan', 'minute': 33, 'type': 'G'},
    {'player': 'David Raum', 'match': 'Germany-Japan', 'minute': 33, 'type': 'A'},
    {'player': 'Ritsu Doan', 'match': 'Germany-Japan', 'minute': 75, 'type': 'G'},
    {'player': 'Takuma Asano', 'match': 'Germany-Japan', 'minute': 83, 'type': 'G'},
    {'player': 'Ko Itakura', 'match': 'Germany-Japan', 'minute': 83, 'type': 'A'},
    {'player': 'Dani Olmo', 'match': 'Spain-Costa Rica', 'minute': 11, 'type': 'G'},
    {'player': 'Marco Asensio', 'match': 'Spain-Costa Rica', 'minute': 21, 'type': 'G'},
    {'player': 'Jordi Alba', 'match': 'Spain-Costa Rica', 'minute': 21, 'type': 'A'},
    {'player': 'Ferran Torres', 'match': 'Spain-Costa Rica', 'minute': 31, 'type': 'G'},
    {'player': 'Jordi Alba', 'match': 'Spain-Costa Rica', 'minute': 31, 'type': 'A'},
    {'player': 'Ferran Torres', 'match': 'Spain-Costa Rica', 'minute': 54, 'type': 'G'},
    {'player': 'Gavi', 'match': 'Spain-Costa Rica', 'minute': 74, 'type': 'G'},
    {'player': 'Alvaro Morata', 'match': 'Spain-Costa Rica', 'minute': 74, 'type': 'A'},
    {'player': 'Carlos Soler', 'match': 'Spain-Costa Rica', 'minute': 90, 'type': 'G'},
    {'player': 'Alvaro Morata', 'match': 'Spain-Costa Rica', 'minute': 92, 'type': 'G'},
    {'player': 'Dani Olmo', 'match': 'Spain-Costa Rica', 'minute': 92, 'type': 'A'},
    {'player': 'Francisco Calvo', 'match': 'Spain-Costa Rica', 'minute': 68, 'type': 'Y'},
    {'player': 'Joel Campbell', 'match': 'Spain-Costa Rica', 'minute': 97, 'type': 'Y'},
    {'player': 'Keysher Fuller', 'match': 'Japan-Costa Rica', 'minute': 81, 'type': 'G'},
    {'player': 'Yeltsin Tejeda', 'match': 'Japan-Costa Rica', 'minute': 81, 'type': 'A'},
    {'player': 'Anthony Contreras', 'match': 'Japan-Costa Rica', 'minute': 41, 'type': 'Y'},
    {'player': 'Miki Yamane', 'match': 'Japan-Costa Rica', 'minute': 44, 'type': 'Y'},
    {'player': 'Celso Borges', 'match': 'Japan-Costa Rica', 'minute': 61, 'type': 'Y'},
    {'player': 'Francisco Calvo', 'match': 'Japan-Costa Rica', 'minute': 70, 'type': 'Y'},
    {'player': 'Ko Itakura', 'match': 'Japan-Costa Rica', 'minute': 84, 'type': 'Y'},
    {'player': 'Wataru Endo', 'match': 'Japan-Costa Rica', 'minute': 93, 'type': 'Y'},
    {'player': 'Alvaro Morata', 'match': 'Spain-Germany', 'minute': 62, 'type': 'G'},
    {'player': 'Jordi Alba', 'match': 'Spain-Germany', 'minute': 62, 'type': 'A'},
    {'player': 'Niclas Fullkrug', 'match': 'Spain-Germany', 'minute': 83, 'type': 'G'},
    {'player': 'Jamal Musiala', 'match': 'Spain-Germany', 'minute': 83, 'type': 'A'},
    {'player': 'Thilo Kehrer', 'match': 'Spain-Germany', 'minute': 37, 'type': 'Y'},
    {'player': 'Sergio Busquets', 'match': 'Spain-Germany', 'minute': 44, 'type': 'Y'},
    {'player': 'Leon Goretzka', 'match': 'Spain-Germany', 'minute': 58, 'type': 'Y'},
    {'player': 'Joshua Kimmich', 'match': 'Spain-Germany', 'minute': 60, 'type': 'Y'},
    {'player': 'Serge Gnabry', 'match': 'Costa Rica-Germany', 'minute': 10, 'type': 'G'},
    {'player': 'David Raum', 'match': 'Costa Rica-Germany', 'minute': 10, 'type': 'A'},
    {'player': 'Yeltsin Tejeda', 'match': 'Costa Rica-Germany', 'minute': 58, 'type': 'G'},
    {'player': 'Manuel Neuer', 'match': 'Costa Rica-Germany', 'minute': 70, 'type': 'G'},
    {'player': 'Juan Pablo Vargas', 'match': 'Costa Rica-Germany', 'minute': 70, 'type': 'A'},
    {'player': 'Kai Havertz', 'match': 'Costa Rica-Germany', 'minute': 73, 'type': 'G'},
    {'player': 'Niclas Fullkrug', 'match': 'Costa Rica-Germany', 'minute': 74, 'type': 'A'},
    {'player': 'Kai Havertz', 'match': 'Costa Rica-Germany', 'minute': 85, 'type': 'G'},
    {'player': 'Serge Gnabry', 'match': 'Costa Rica-Germany', 'minute': 85, 'type': 'A'},
    {'player': 'Niclas Fullkrug', 'match': 'Costa Rica-Germany', 'minute': 89, 'type': 'G'},
    {'player': 'Leroy Sane', 'match': 'Costa Rica-Germany', 'minute': 89, 'type': 'A'},
    {'player': 'Oscar Duarte', 'match': 'Costa Rica-Germany', 'minute': 76, 'type': 'Y'},
    {'player': 'Alvaro Morata', 'match': 'Japan-Spain', 'minute': 11, 'type': 'G'},
    {'player': 'Cesar Azpilicueta', 'match': 'Japan-Spain', 'minute': 11, 'type': 'A'},
    {'player': 'Ritsu Doan', 'match': 'Japan-Spain', 'minute': 48, 'type': 'G'},
    {'player': 'Junya Ito', 'match': 'Japan-Spain', 'minute': 48, 'type': 'A'},
    {'player': 'Ao Tanaka', 'match': 'Japan-Spain', 'minute': 51, 'type': 'G'},
    {'player': 'Kaoru Mitoma', 'match': 'Japan-Spain', 'minute': 51, 'type': 'A'},
    {'player': 'Ko Itakura', 'match': 'Japan-Spain', 'minute': 39, 'type': 'Y'},
    {'player': 'Shogo Taniguchi', 'match': 'Japan-Spain', 'minute': 44, 'type': 'Y'},
    {'player': 'Maya Yoshida', 'match': 'Japan-Spain', 'minute': 45, 'type': 'Y'},
]

df = pd.DataFrame(data)
df.to_csv('events.csv')

df

                  player             match  minute type
0    Alexis Mac Allister  Poland-Argentina      46    G
1          Nahuel Molina  Poland-Argentina      46    A
2         Julian Alvarez  Poland-Argentina      67    G
3         Enzo Fernandez  Poland-Argentina      67    A
4           Marcos Acuna  Poland-Argentina      49    Y
..                   ...               ...     ...  ...
99             Ao Tanaka       Japan-Spain      51    G
100         Kaoru Mitoma       Japan-Spain      51    A
101           Ko Itakura       Japan-Spain      39    Y
102      Shogo Taniguchi       Japan-Spain      44    Y
103         Maya Yoshida       Japan-Spain      45    Y

[104 rows x 4 columns]